# Generated by Django 3.2.16 on 2022-10-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='files',
            field=models.ManyToManyField(to='produto.Imagens'),
        ),
    ]
