# Generated by Django 3.2.16 on 2022-10-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='files',
            field=models.ManyToManyField(blank=True, to='produto.Imagens'),
        ),
    ]
