# Generated by Django 3.2.16 on 2022-10-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_itempedido_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedido.cupomdesconto'),
        ),
    ]
